# Generated by Django 4.2.4 on 2024-08-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('bodytype', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('yearfrom', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('yearto', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('uuid', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('drivetype', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('enginetype', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('enginecodes', models.TextField()),
                ('cylinders', models.IntegerField()),
                ('valve', models.IntegerField()),
            ],
        ),
    ]
