# Generated by Django 4.2.4 on 2025-11-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('brands', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brandpdcts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('loaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Carmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifacturer_code', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('models', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('vinequ', models.JSONField(blank=True, default=list, null=True)),
                ('bodytype', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('yearfrom', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('yearto', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('uuid', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('drivetype', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('enginetype', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('enginecodes', models.TextField()),
                ('cylinders', models.IntegerField()),
                ('valve', models.IntegerField()),
                ('carinfo', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cartarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('targets', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbfirst', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchdb', models.BooleanField(default=False)),
                ('accounts', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commoncode', models.JSONField(blank=True, default=list, null=True)),
                ('car_codes', models.JSONField(blank=True, default=list, null=True)),
                ('features', models.JSONField(blank=True, default=dict, null=True)),
                ('fullName', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('brandid', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('brandref', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('refs', models.JSONField(blank=True, default=list, null=True)),
                ('oems', models.JSONField(blank=True, default=list, null=True)),
                ('ean', models.JSONField(blank=True, default=list, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('image', models.TextField(blank=True, default=None, null=True)),
                ('categoryid', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('assemblyGroups', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refbrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('brands', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refpdcts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('loaded', models.BooleanField(default=False)),
                ('brands', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Systemstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=900)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('forclient', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
    ]
