# Generated by Django 4.2.4 on 2024-08-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_codes', models.TextField(blank=True, default=None, null=True)),
                ('features', models.TextField(blank=True, default=None, null=True)),
                ('fullName', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('brandref', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('refs', models.TextField(blank=True, default=None, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('image', models.TextField(blank=True, default=None, null=True)),
                ('categoryid', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
    ]
