# Generated by Django 4.2.4 on 2024-08-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ean',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='oems',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='car_codes',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='refs',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
