# Generated by Django 5.0.7 on 2024-08-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0003_products_ean_products_oems_alter_products_car_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='car_codes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ean',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='features',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='oems',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='refs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
