# Generated by Django 5.0.7 on 2024-08-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0004_alter_products_car_codes_alter_products_ean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='assemblyGroups',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
