# Generated by Django 5.0.7 on 2024-08-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0005_products_assemblygroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brandid',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
