# Generated by Django 5.0.7 on 2024-08-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0008_brandpdcts'),
    ]

    operations = [
        migrations.CreateModel(
            name='refpdcts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('loaded', models.BooleanField(default=False)),
            ],
        ),
    ]
