# Generated by Django 5.0.7 on 2024-08-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0009_refpdcts'),
    ]

    operations = [
        migrations.AddField(
            model_name='refpdcts',
            name='brands',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
