# Generated by Django 5.0.7 on 2024-08-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0010_refpdcts_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifacturer_code', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('models', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cartarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('targets', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
