# Generated by Django 5.0.7 on 2024-08-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0012_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
