# Generated by Django 5.0.7 on 2024-08-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0014_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='refbrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('brands', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
