# Generated by Django 5.0.7 on 2024-09-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0015_refbrands'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='carinfo',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
