# Generated by Django 5.0.7 on 2024-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0016_cars_carinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='vinequ',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
