# Generated by Django 5.0.7 on 2024-09-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0017_cars_vinequ'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='commoncode',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
