# Generated by Django 4.2.4 on 2024-10-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0018_products_commoncode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchdb', models.BooleanField(default=False)),
                ('accounts', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Systemstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=900)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('forclient', models.BooleanField(default=False)),
            ],
        ),
    ]
